server.port=8081
spring.application.name=leaderboard-service

# Enable the H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Hibenate configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.sql.init.mode=always

# JPA logging options
spring.jpa.show-sql=off
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=info

# Actuator - /health monitoring endpoints
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Leaderboard-service
info.app.description=Leaderboard

# K8S liveness and readiness probes
management.endpoint.health.probe.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# RabbitMQ config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Cache configs
spring.cache.cache-names=topScores
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=60s

# RabbitConfig
tenvia.rabbit.exchange=game.exchange
tenvia.rabbit.routing-key=score.submitted
tenvia.rabbit.queue=scoring.queue

# Grafana-4701 dashboard
management.metrics.tags.application=${spring.application.name}