server.port=8081
spring.application.name=leaderboard-service
# Enable the H2 console
spring.h2.console.enabled=true
# Set the path to access the H2 console
spring.h2.console.path=/h2-console
# Configure the in-memory database URL (optional, defaults to testdb)
spring.datasource.url=jdbc:h2:mem:testdb
# Default credentials
spring.datasource.username=sa
spring.datasource.password=

# Disable auto create/update table based of entity mapping
spring.jpa.hibernate.ddl-auto=update
# Enable batch fetching
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.sql.init.mode=always

# Logging options
# Show the SQL in the console
spring.jpa.show-sql=off
# Format the SQL so it's readable
spring.jpa.properties.hibernate.format_sql=true
# Show the actual values being passed to the "?" parameters
logging.level.org.hibernate.orm.jdbc.bind=info

# Actuator - /health monitoring endpoints
management.endpoints.web.exposure.include=health,info
# Show all details
management.endpoint.health.show-details=always
# Enable the /actuator/info endpoint
management.info.env.enabled=true
# Name the service for /info - add more details to include in the json response
info.app.name=Leaderboard-service
info.app.description=Leaderboard
# K8S liveness and readiness probes
management.endpoint.health.probe.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# RabbitMQ config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Cache configs
spring.cache.cache-names=topScores
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=60s
