apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tenvia-app
  name: tenvia-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenvia-app
  strategy: {}
  template:
    metadata:
      labels:
        app: tenvia-app
    spec:
      containers:
      - image: docker.io/library/tenvia:latest
        name: tenvia-app
        imagePullPolicy: Never
        resources: {}
status: {}
