apiVersion: v1
kind: Service
metadata:
  name: tenvia-service
spec:
  selector:
    app: tenvia-app  # Need to match deployment label
  ports:
    - protocol: TCP
      port: 8080       # Minikube cluster app port
      targetPort: 8080 # The port in host machine  with Spring Boot app running and listening on
  type: ClusterIP