server.port=8080
# To be overridden in docker compose
question.service.port=8083
services.question-service.url=${QUESTION_SERVICE_URL:http://localhost:${question.service.port}}

# Enable the H2 console
spring.h2.console.enabled=true
# Set the path to access the H2 console
spring.h2.console.path=/h2-console
# Configure the in-memory database URL (optional, defaults to testdb)
spring.datasource.url=jdbc:h2:mem:testdb
# Default credentials
spring.datasource.username=sa
spring.datasource.password=

# Disable auto create/update table based of entity mapping
spring.jpa.hibernate.ddl-auto=update
# Enable batch fetching
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.sql.init.mode=always

# Ensures _schema.sql runs before data_old.sql
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

# Force Hibernate to initialize the schema BEFORE running data_old.sql
spring.jpa.defer-datasource-initialization=true

# Logging options
# Show the SQL in the console
spring.jpa.show-sql=off
# Format the SQL so it's readable
spring.jpa.properties.hibernate.format_sql=true
# Show the actual values being passed to the "?" parameters
logging.level.org.hibernate.orm.jdbc.bind=info

# Actuator - Health monitoring endpoints
management.endpoints.web.exposure.include=health,info,prometheus
# Add tags to all metrics to be used in EKS as adding a label to EKS service will allow Prometheus to see new pods and pulling the data
management.metrics.tags.application=tenvia-app
# Show all details
management.endpoints.health.show-details=always
# Enable the /actuator/info endpoint
management.info.env.enabled=true
# Name the service for /info - add more details to include in the json response
info.app.name=Tenvia App
info.app.description=QuizGame
# K8S liveness and readiness probes
management.endpoint.health.probe.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true


# RabbitMQ config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Session terminator rate
session.terminator.schedule.rate=60000
session.duration.in.seconds=900
