# Deployment tenvia-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenvia-app
  labels:
    app: tenvia-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenvia-app
  template:
    metadata:
      labels:
        app: tenvia-app
    spec:
      containers:
      - name: tenvia-app
        image: tenvia-app:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"

        readinessProbe:
          httpGet:
            path: "/actuator/health/readiness"
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: tenvia-app
spec:
  selector:
    app: tenvia-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080